#Minecraft server properties
#Sun Oct 04 15:20:05 PDT 2026
accepts-transfers=false
allow-flight=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=false
bug-report-link=
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=arena
level-seed=0
level-type=minecraft\:flat
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=IE7tFAvHQRJNFYQn4Eh27J3iBC6EkRldXoBnN9yt
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=8
max-tick-time=60000
max-world-size=29999984
motd=CraftArenaBench
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=local-dev-only
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=6
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=6
white-list=false
